name: Build toolchain on release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-toolchain:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt update 
          sudo apt install -y gperf help2man libncurses5-dev libtool-bin libstdc++6 meson ninja-build

      - name: Configure and make crosstool-ng
        run: |
          mkdir builder
          ./bootstrap
          ./configure --prefix=$(pwd)/builder
          make
          make install

      - name: Build toolchain
        run: |
          cp sams-config/ct-ng-menuconfig.conf builder/.config
          cd builder
          bin/ct-ng build

      - name: Yay it worked! Now, where is my toolchain located?
        run: |
          ls -la builder
          ls -la .
          ls -la ..

  #     - name: Upload build output
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: build-output-android30
  #         path: libck-android30.a

  # create-release:
  #   runs-on: ubuntu-20.04
  #   needs: [build-macos, build-android, build-macos-arm64]
  #   steps:
  #     - name: Get build output macos11
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: build-output-macos11

  #     - name: Get build output android30
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: build-output-android30

  #     - name: Get build output macos-arm64
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: build-output-macos-arm64

  #     - name: Create release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: |
  #           include.zip
  #           libck-macos11.a
  #           libck-android30.a
  #           libck-macos-arm64.a
  #           LICENSE
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
