name: Build toolchain on release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-toolchain:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt update 
          sudo apt install -y gperf help2man libncurses5-dev libtool-bin libstdc++6 meson ninja-build

      - name: Configure and make crosstool-ng
        run: |
          mkdir builder
          ./bootstrap
          ./configure --prefix=$(pwd)/builder
          make
          make install

      - name: Build toolchain
        run: |
          cp sams-config/ct-ng-menuconfig.conf builder/.config
          cd builder
          bin/ct-ng build

      - name: tar toolchain
        run: tar cJf arm-rpi-linux-gnueabihf.tar.xz -C $HOME/x-tools arm-rpi-linux-gnueabihf

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: arm-rpi-linux-gnueabihf.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
